INSERT INTO public.plan (id, codigo, nombre, descripcion) VALUES 
(1, 'DIR', 'DIRECCIONAMIENTO ESTRATEGICO', ''),
(2, 'PLE', 'PLANEACION ESTRATEGICA', ''),
(3, 'HAB', 'HABILITACION', ''),
(4, 'PMA', 'PLAN DE MEJORAMIENTO DE ACREDITACION', ''),
(5, 'PCO', 'PLAN DE COMITES', ''),
(6, 'PPR', 'PLAN DE PROGRAMAS', ''),
(7, 'PPR', 'PLAN DE PROCESOS', ''),
(8, 'PAU', 'PLAN DE AUDITORIAS', ''),
(9, 'PUF', 'PLAN DE UNIDADES FUNCIONALES', ''),
(10, 'PIE', 'PLAN INSTITUCIONAL DE EDUCACIÓN', ''),
(11, 'NIN', 'NINGUNO', '');
