package com.medihelp.presupuesto.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CentroCostoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroCostoAllPropertiesEquals(CentroCosto expected, CentroCosto actual) {
        assertCentroCostoAutoGeneratedPropertiesEquals(expected, actual);
        assertCentroCostoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroCostoAllUpdatablePropertiesEquals(CentroCosto expected, CentroCosto actual) {
        assertCentroCostoUpdatableFieldsEquals(expected, actual);
        assertCentroCostoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroCostoAutoGeneratedPropertiesEquals(CentroCosto expected, CentroCosto actual) {
        assertThat(expected)
            .as("Verify CentroCosto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroCostoUpdatableFieldsEquals(CentroCosto expected, CentroCosto actual) {
        assertThat(expected)
            .as("Verify CentroCosto relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroCostoUpdatableRelationshipsEquals(CentroCosto expected, CentroCosto actual) {
        // empty method
    }
}
