package com.medihelp.presupuesto.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RubroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubroAllPropertiesEquals(Rubro expected, Rubro actual) {
        assertRubroAutoGeneratedPropertiesEquals(expected, actual);
        assertRubroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubroAllUpdatablePropertiesEquals(Rubro expected, Rubro actual) {
        assertRubroUpdatableFieldsEquals(expected, actual);
        assertRubroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubroAutoGeneratedPropertiesEquals(Rubro expected, Rubro actual) {
        assertThat(expected)
            .as("Verify Rubro auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubroUpdatableFieldsEquals(Rubro expected, Rubro actual) {
        assertThat(expected)
            .as("Verify Rubro relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRubroUpdatableRelationshipsEquals(Rubro expected, Rubro actual) {
        // empty method
    }
}
