package com.medihelp.presupuesto.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoRecursoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoRecursoAllPropertiesEquals(TipoRecurso expected, TipoRecurso actual) {
        assertTipoRecursoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoRecursoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoRecursoAllUpdatablePropertiesEquals(TipoRecurso expected, TipoRecurso actual) {
        assertTipoRecursoUpdatableFieldsEquals(expected, actual);
        assertTipoRecursoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoRecursoAutoGeneratedPropertiesEquals(TipoRecurso expected, TipoRecurso actual) {
        assertThat(expected)
            .as("Verify TipoRecurso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoRecursoUpdatableFieldsEquals(TipoRecurso expected, TipoRecurso actual) {
        assertThat(expected)
            .as("Verify TipoRecurso relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoRecursoUpdatableRelationshipsEquals(TipoRecurso expected, TipoRecurso actual) {
        // empty method
    }
}
