package com.medihelp.presupuesto.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UnidadFuncionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadFuncionalAllPropertiesEquals(UnidadFuncional expected, UnidadFuncional actual) {
        assertUnidadFuncionalAutoGeneratedPropertiesEquals(expected, actual);
        assertUnidadFuncionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadFuncionalAllUpdatablePropertiesEquals(UnidadFuncional expected, UnidadFuncional actual) {
        assertUnidadFuncionalUpdatableFieldsEquals(expected, actual);
        assertUnidadFuncionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadFuncionalAutoGeneratedPropertiesEquals(UnidadFuncional expected, UnidadFuncional actual) {
        assertThat(expected)
            .as("Verify UnidadFuncional auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadFuncionalUpdatableFieldsEquals(UnidadFuncional expected, UnidadFuncional actual) {
        assertThat(expected)
            .as("Verify UnidadFuncional relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadFuncionalUpdatableRelationshipsEquals(UnidadFuncional expected, UnidadFuncional actual) {
        // empty method
    }
}
